# Generated by Django 3.1.2 on 2020-10-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coaster',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fandom_good',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='home_decor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
