# Generated by Django 3.1.2 on 2020-10-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201015_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coaster',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1200001),
            preserve_default=False,
        ),
    ]
