# Generated by Django 3.1.2 on 2020-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201016_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coaster',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
