# Generated by Django 3.1.2 on 2020-10-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201016_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coaster',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fandom_good',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='home_decor',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
